# Generated by Django 5.0.4 on 2024-05-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_course_instructor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
